name: "Build & Test"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test_doxygen:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ssciwr/doxygen-install@v1
        with:
          version: "1.9.6"
      - uses: ts-graphviz/setup-graphviz@v1
      - name: Prepare Doxygen Config
        run: echo "PROJECT_NUMBER = ${GITHUB_REF}" >> Doxyfile
      - name: Run Doxygen
        run: doxygen
