name: "Pages"

on:
  push:
    branches: [ "main" ]

jobs:
  github_pages:
    runs-on: ubuntu-latest
    needs: doxygen
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: doxygen-html
      - run: unzip html.zip
      - run: |
          cd html
          git add -A
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m 'deploy'
      - uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./html
